config/routes.rb
Slug57::Application.routes.draw do
  resources :line_items

  resources :carts

  get "store/index"

  resources :barracks

  resources :on_loans

  resources :items

  resources :cadets
  root :to => 'store#index', :as => 'store'

end

app/models/barrack.rb
class Barrack < ActiveRecord::Base
end

app/controllers/barracks_controller.rb
class BarracksController < ApplicationController
  # GET /barracks
  # GET /barracks.json
  def index
    @barracks = Barrack.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @barracks }
    end
  end

  # GET /barracks/1
  # GET /barracks/1.json
  def show
    @barrack = Barrack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @barrack }
    end
  end

  # GET /barracks/new
  # GET /barracks/new.json
  def new
    @barrack = Barrack.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @barrack }
    end
  end

  # GET /barracks/1/edit
  def edit
    @barrack = Barrack.find(params[:id])
  end

  # POST /barracks
  # POST /barracks.json
  def create
    @barrack = Barrack.new(params[:barrack])

    respond_to do |format|
      if @barrack.save
        format.html { redirect_to @barrack, notice: 'Barrack was successfully created.' }
        format.json { render json: @barrack, status: :created, location: @barrack }
      else
        format.html { render action: "new" }
        format.json { render json: @barrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /barracks/1
  # PUT /barracks/1.json
  def update
    @barrack = Barrack.find(params[:id])

    respond_to do |format|
      if @barrack.update_attributes(params[:barrack])
        format.html { redirect_to @barrack, notice: 'Barrack was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @barrack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barracks/1
  # DELETE /barracks/1.json
  def destroy
    @barrack = Barrack.find(params[:id])
    @barrack.destroy

    respond_to do |format|
      format.html { redirect_to barracks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/barracks_helper.rb
module BarracksHelper
end

app/views/barracks/_form.html.erb
<%= form_for(@barrack) do |f| %>
  <% if @barrack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barrack.errors.count, "error") %> prohibited this barrack from being saved:</h2>

      <ul>
      <% @barrack.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rackName %><br />
    <%= f.text_field :rackName %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/barracks/edit.html.erb
<h1>Editing barrack</h1>

<%= render 'form' %>

<%= link_to 'Show', @barrack %> |
<%= link_to 'Back', barracks_path %>

app/views/barracks/index.html.erb
<h1>Listing barracks</h1>

<table>
  <tr>
    <th>Rackname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @barracks.each do |barrack| %>
  <tr>
    <td><%= barrack.rackName %></td>
    <td><%= link_to 'Show', barrack %></td>
    <td><%= link_to 'Edit', edit_barrack_path(barrack) %></td>
    <td><%= link_to 'Destroy', barrack, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Barrack', new_barrack_path %>

app/views/barracks/new.html.erb
<h1>New barrack</h1>

<%= render 'form' %>

<%= link_to 'Back', barracks_path %>

app/views/barracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rackname:</b>
  <%= @barrack.rackName %>
</p>


<%= link_to 'Edit', edit_barrack_path(@barrack) %> |
<%= link_to 'Back', barracks_path %>