config/routes.rb
Slug57::Application.routes.draw do
  resources :line_items

  resources :carts

  get "store/index"

  resources :barracks

  resources :on_loans

  resources :items

  resources :cadets
  root :to => 'store#index', :as => 'store'

end

app/models/cadet.rb
class Cadet < ActiveRecord::Base
end

app/controllers/cadets_controller.rb
class CadetsController < ApplicationController
  # GET /cadets
  # GET /cadets.json
  def index
    @cadets = Cadet.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cadets }
    end
  end

  # GET /cadets/1
  # GET /cadets/1.json
  def show
    @cadet = Cadet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cadet }
    end
  end

  # GET /cadets/new
  # GET /cadets/new.json
  def new
    @cadet = Cadet.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cadet }
    end
  end

  # GET /cadets/1/edit
  def edit
    @cadet = Cadet.find(params[:id])
  end

  # POST /cadets
  # POST /cadets.json
  def create
    @cadet = Cadet.new(params[:cadet])

    respond_to do |format|
      if @cadet.save
        format.html { redirect_to @cadet, notice: 'Cadet was successfully created.' }
        format.json { render json: @cadet, status: :created, location: @cadet }
      else
        format.html { render action: "new" }
        format.json { render json: @cadet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cadets/1
  # PUT /cadets/1.json
  def update
    @cadet = Cadet.find(params[:id])

    respond_to do |format|
      if @cadet.update_attributes(params[:cadet])
        format.html { redirect_to @cadet, notice: 'Cadet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cadet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadets/1
  # DELETE /cadets/1.json
  def destroy
    @cadet = Cadet.find(params[:id])
    @cadet.destroy

    respond_to do |format|
      format.html { redirect_to cadets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/cadets_helper.rb
module CadetsHelper
end

app/views/cadets/_form.html.erb
<%= form_for(@cadet) do |f| %>
  <% if @cadet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cadet.errors.count, "error") %> prohibited this cadet from being saved:</h2>

      <ul>
      <% @cadet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first %><br />
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br />
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :rack %><br />
    <%= f.number_field :rack %>
  </div>
  <div class="field">
    <%= f.label :roomnum %><br />
    <%= f.number_field :roomnum %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cadets/edit.html.erb
<h1>Editing cadet</h1>

<%= render 'form' %>

<%= link_to 'Show', @cadet %> |
<%= link_to 'Back', cadets_path %>

app/views/cadets/index.html.erb
<h1>Listing cadets</h1>

<table>
  <tr>
    <th>First</th>
    <th>Last</th>
    <th>Rack</th>
    <th>Roomnum</th>
    <th>Company</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cadets.each do |cadet| %>
  <tr>
    <td><%= cadet.first %></td>
    <td><%= cadet.last %></td>
    <td><%= cadet.rack %></td>
    <td><%= cadet.roomnum %></td>
    <td><%= cadet.company %></td>
    <td><%= link_to 'Show', cadet %></td>
    <td><%= link_to 'Edit', edit_cadet_path(cadet) %></td>
    <td><%= link_to 'Destroy', cadet, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cadet', new_cadet_path %>

app/views/cadets/new.html.erb
<h1>New cadet</h1>

<%= render 'form' %>

<%= link_to 'Back', cadets_path %>

app/views/cadets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>First:</b>
  <%= @cadet.first %>
</p>

<p>
  <b>Last:</b>
  <%= @cadet.last %>
</p>

<p>
  <b>Rack:</b>
  <%= @cadet.rack %>
</p>

<p>
  <b>Roomnum:</b>
  <%= @cadet.roomnum %>
</p>

<p>
  <b>Company:</b>
  <%= @cadet.company %>
</p>


<%= link_to 'Edit', edit_cadet_path(@cadet) %> |
<%= link_to 'Back', cadets_path %>